project:
  type: website
  output-dir: docs

website:
  title: "Finn Mayhew"
  favicon: ./images/favicon.png
  search: false
  navbar:
    search: false
    background: white
    foreground: "#675ae8"
    left:
      - href: music.qmd
        text: Music
      - href: physics.qmd
        text: Physics
      - href: sudoku.qmd
        text: Sudoku
      - href: schedule.qmd
        text: Schedule with me
      - href: old_things.qmd
        text: Old things

format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css
    toc: true
