project:
  type: website
  output-dir: docs

website:
  title: "Finn Mayhew"
  favicon: ./images/favicon.png
  search: false
  navbar:
    search: false
    background: black
    left:
      - href: music.qmd
        text: Music
      - href: physics.qmd
        text: Physics
      - href: old_things.qmd
        text: Old things
      - href: schedule.qmd
        text: Schedule with me
  page-footer:
    center: 
      - icon: instagram
        href: https://www.instagram.com/finnmayhew_/
      - icon: mastodon
        href: https://mastodon.social/@finnmayhew
      - icon: pinterest 
        href: https://www.pinterest.com/finnmayhew_/

format:
  html:
    theme: [darkly, theme.scss]
    css: styles.css
    toc: true
